language: c

env:
 - RACKET_VERSION=5.3.2
 - RACKET_VERSION=5.3.5
 - RACKET_VERSION=5.3.6
 - RACKET_VERSION=5.92
 - RACKET_VERSION=HEAD

before_install:
 - curl https://raw.github.com/greghendershott/travis-racket/master/install-racket.sh | sh

install:

before_script:

script:
 - /usr/racket/bin/raco link rackjure
 - cd rackjure
 - /usr/racket/bin/raco make main.rkt
 - /usr/racket/bin/raco test -x .

after_script:
